name: 07-contexts
run-name: My custom workflow run name - ${{inputs.debug}}
env:
    MY_WORKFLOW_VAR: workflow
    MY_OVERWRITTEN_VAR: workflow
on: 
    push: 
    workflow_dispatch:
        inputs:
            debug:
                description: 'Debug mode'
                type: boolean           
                default: false 
        
jobs:
    echo-data:
        env:
            MY_JOB_VAR: job
            MY_OVERWRITTEN_VAR: job
        runs-on: ubuntu-latest
        steps:
            - name: Show info
              run: |
                echo "Nombre del evento: ${{github.event_name}}"
                echo "Ref: ${{github.ref}}"
                echo "SHA: ${{github.sha}}"
                echo "Actor: ${{github.actor}}"
                echo "Flujo de trabajo: ${{github.workflow}}"
                echo "ID de ejecución: ${{github.run_id}}"
                echo "Número de ejecución: ${{github.run_number}}"
            - name: Retrieve Variable
              run: echo ${{vars.MY_VAR}}
            - name: Print Env Variables
              env:
                MY_WORKFLOW_VAR: step
              run: |
                echo "Workflow env:  ${{env.MY_WORKFLOW_VAR}} aquí" 
                echo "Overwritten env:: ${{env.MY_OVERWRITTEN_VAR}} aquí"
            - name: Print Env Variables
              run: |
                echo "Workflow env:  ${{env.MY_WORKFLOW_VAR}} aquí" 
                echo "Overwritten env:: ${{env.MY_OVERWRITTEN_VAR}} aquí"


