name: 08 - Expressions
on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Debug mode'
        type: boolean
        default: false
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "${{inputs.debug}} Print start-up"
        if: ${{inputs.debug}}
        run: |
          echo "Triggered by ${{github.event_name}}"
          echo "branch: ${{github.ref}}"
          echo "Commit: ${{github.sha}}"
      - name: "${{inputs.debug}} Print only is main" 
        if: inputs.debug && github.ref_name == 'main'
        run: echo "This is the main branch"