name: 14 - Using Cache

on:
  push:
  workflow_dispatch:
    inputs:
      use-cache:
        description: 'Whether to execute cache step'
        type: boolean
        required: false
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: my-app/react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Download cached dependencies
        if: ${{github.event.inputs.use-cache == 'true'}}
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('14-caching/react-app/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Testing
        run: npm run test

      - name: Building
        run: npm run build

      - name: Deploying to nonprod
        run: echo "Deploying to nonprod"
