name: 15 - Working with Artifacts

on:
  push:
  workflow_dispatch:
    inputs:
      use-cache:
        description: 'Whether to execute cache step'
        type: boolean
        required: false
        default: true

jobs:
  test-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: my-app/react-app/
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Download cached dependencies
        if: ${{github.event.inputs.use-cache == 'true'}}
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('15-artifacts/react-app/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Testing
        run: npm run test

      - name: Building
        run: npm run build

      - name: Uploading artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-app
          path: my-app/react-app/build
  deploy:
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: my-app
          path: my-app