name: 16 - Working with Matrices
on:
  workflow_dispatch:

jobs:
  backwards-compatibility:
    runs-on: ubuntu-latest
    name: ${{matrix.so}}-${{matrix.node}}
    strategy:
      fail-fast: true
      matrix:
        node: [18.x,20.x,21.x]
        so: [ubuntu-latest,windows-latest]
        include:
          - so: ubuntu-latest 
            node: 16.x
          - so: ubuntu-latest 
            node: 21.x
            tag: experimental
        exclude:
          - so: windows-latest 
            node: 20.x 
          
    steps:
      - name: Fail if experimental
        if: matrix.tag == 'experimental'
        run: exit 1
      - run: |
         echo "configurando ${{matrix.so}}-${{matrix.node}}"
         sleep 10
